### PR TITLE
Fix build on unix

### PR DESCRIPTION
**Pull request by crackcomm**
It failed to build on unix.

### CODE REVIEW

**Comment by Yawning** [comment]
Github is case insensitive when cloning, and I use `yawning` all throughout my code/various other projects. Won't fix.

**Comment by Yawning** [comment]
For posterity, I'd be more inclined to fix something like this if it broke for something like this:

```
ypres :: ~ % export GOPATH=/tmp/gooo                           
ypres :: ~ % go get -u github.com/yawning/bulb
ypres :: ~ % ls $GOPATH/src/github.com/yawning/bulb/                            
cmd_authenticate.go  conn.go    LICENSE      response.go
cmd_onion.go         dialer.go  listener.go  status.go
cmd_protocolinfo.go  examples   README.md    utils
```

But it doesn't, and neither does importing `github.com/yawning/bulb`.

**Comment by crackcomm** [comment]
It broke in project with Godeps saved using `godep save`, bulb was installed using `go get` on Windows.

**Comment by crackcomm** [comment]
> Github is case insensitive when cloning

I didn't know that, it seems reasonable to solve it in a different way.

**Comment by Yawning** [comment]
I don't use `godep`.  If it was installed on windows using `go get github.com/yawning/bulb` and it broke when restoring there's an issue somewhere, and I'd be more inclined to fix it.  Otherwise, "Well, `import`/`go get` it with a lower case y, and life is good".

If I'm going to go and edit all my code that refers to it in the lowercase form, I may just move the library to a torproject.org repo, where yawning is all lowercase.

**Pull request closed without merging**
